models/Certificate.php
<?php

namespace app\models;

use app\imagine\Image;
use Yii;

/**
 * This is the model class for table "certificates".
 *
 * @property int $id
 * @property int $template_id
 * @property int $created_at
 * @property string $email
 *
 * @property CertValue $certValues
 * @property Template $template
 */
class Certificate extends \yii\db\ActiveRecord
{

    public function init()
    {

        if(!Yii::$app->user->isGuest) {
            $this->email = Yii::$app->user->identity->email;
        }

        parent::init();
    }


    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'certificates';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['template_id', 'email'], 'required'],
            [['template_id', 'created_at'], 'integer'],
            [['email'], 'string', 'max' => 255],
            [['template_id'], 'exist', 'skipOnError' => true, 'targetClass' => Template::className(), 'targetAttribute' => ['template_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'template_id' => 'Template ID',
            'created_at' => 'Created At',
            'email' => 'Email',
            'title' => 'Название'
        ];
    }

    public function beforeSave($insert)
    {
        $this->created_at = time();
        return parent::beforeSave($insert);
    }

    public function afterDelete()
    {
        $path = $this->getFullPath();
        if(file_exists($path)) {
            unlink($path);
        }

        parent::afterDelete();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCertValues()
    {
        return $this->hasOne(CertValue::className(), ['cert_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTemplate()
    {
        return $this->hasOne(Template::className(), ['id' => 'template_id']);
    }

    public function render()
    {
        $cert = new Image($this->template->getWebRootPath());

        /** @var CertValue[] $values */
        $values = CertValue::find()->where(['cert_id' => $this->id])->with('block')->all();

        foreach ($values as $value) {
            $cert->drawText($value->value, $value->block);
        }

        $cert->save($this->getFullPath());
    }

    public function show()
    {
        $cert = new Image($this->template->getWebRootPath());

        /** @var CertValue[] $values */
        $values = CertValue::find()->where(['cert_id' => $this->id])->with('block')->all();

        foreach ($values as $value) {
            $cert->drawText($value->value, $value->block);
        }

        return $cert->show();
    }


    public function getPath()
    {
        $name = md5($this->id);
        return '/certificates/' . substr($name, 0, 2) . '/' . substr($name, 2, 2) . '/' . $name . '.jpg';
    }

    public function getFullPath()
    {
        $name = md5($this->id);
        $path = Yii::getAlias('@webroot/certificates/' . substr($name, 0, 2));
        if (!file_exists($path)) {
            mkdir($path);
        }

        $path .= '/' . substr($name, 2, 2);
        if (!file_exists($path)) {
            mkdir($path);
        }

        return $path . '/' . $name . '.jpg';
    }

}

controllers/CertificateController.php
<?php


namespace app\controllers;


use app\imagine\Image;
use app\models\Block;
use app\models\Certificate;
use app\models\CertValue;
use app\models\SignupForm;
use app\models\Template;
use app\models\Type;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class CertificateController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create'],
                        'allow' => true,
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    public function actionIndex()
    {
        return $this->render('index', [
            'model' => Template::find()
                ->where(['status' => Template::STATUS_ACTIVE])
                ->orderBy(['id' => SORT_DESC])->all()
        ]);
    }

    public function actionMy()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Certificate::find()
                ->with('template')
                ->where(['email' => \Yii::$app->user->identity->email])
                ->orderBy(['id' => SORT_DESC])
        ]);

        return $this->render('my', [
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * @param null|int $id
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws \Exception
     */
    public function actionCreate(int $id = null)
    {
        /** @var Template $template */
        $template = is_null($id) ?
            Template::find()->orderBy(['id' => SORT_DESC])->one() :
            Template::find()->where(['id' => $id])->one();

        $certificate = new Certificate();

        /** @var Type $fieldType */
        $fieldType = Type::find()->select(['id'])->where(['type' => 'field'])->asArray()->all();

        $ids = [];
        foreach ($fieldType as $item) {
            $ids[] = $item['id'];
        }

        /** @var Block[] $fieldBlocks */
        $fieldBlocks = Block::find()
            ->with('type')
            ->andWhere(['template_id' => $template->id])
            ->andWhere(['type_id' => $ids])
            ->all();

        $certValue = new CertValue();

        if ($certificate->load(\Yii::$app->request->post()) && $certificate->validate()) {
            $transaction = \Yii::$app->db->beginTransaction();

            try {
                if(!($user = User::find()->where(['email' => $certificate->email]))->one()) {
                    $form = new SignupForm([
                        'username' => $certificate->email,
                        'email' => $certificate->email,
                        'password' => SignupForm::getRandomPassword(),
                    ]);
                    $form->signup();
                }

                $certificate->save();


                /** @var Block[] $allBlocks */
                $allBlocks = Block::find()
                    ->with('type')
                    ->andWhere(['template_id' => $id])
                    ->all();

                foreach ($allBlocks as $block) {
                    $model = new CertValue();
                    $model->cert_id = $certificate->id;
                    $model->block_id = $block->id;
                    $model->value = $block->getValue($certificate);
                    $model->save();
                }
                $transaction->commit();

                return $this->redirect(['/certificate/view', 'id' => $certificate->id]);
            } catch (\Exception $e) {
                $transaction->rollBack();
                throw $e;
            }
        }

        if (!$template) {
            throw new NotFoundHttpException('Сертификат не найден');
        }

        return $this->render('create', [
            'template' => $template,
            'certificate' => $certificate,
            'blocks' => $fieldBlocks,
            'certValue' => $certValue,
        ]);
    }


    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $user = \Yii::$app->user;
        if (!$user->can('admin') && $user->identity->email != $model->email) {
            throw new ForbiddenHttpException('Отказано в доступе');
        }

        return $this->render('view', ['model' => $model]);
    }


    public function actionImg($id)
    {
        $model = $this->findModel($id);
        $user = \Yii::$app->user;
        if (!$user->can('admin') && $user->identity->email != $model->email) {
            throw new ForbiddenHttpException('Отказано в доступе');
        }

        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->headers->add('content-type', 'image/png');
        \Yii::$app->response->data = $model->show();
        return \Yii::$app->response;
    }


    public function actionDownload($id)
    {
        $model = $this->findModel($id);
        $user = \Yii::$app->user;
        if (!$user->can('admin') && $user->identity->email != $model->email) {
            throw new ForbiddenHttpException('Отказано в доступе');
        }

        \Yii::$app->response->format = Response::FORMAT_RAW;
        \Yii::$app->response->setDownloadHeaders($model->id . ".jpg");
        \Yii::$app->response->headers->add('content-type', 'image/png');
        \Yii::$app->response->data = $model->show();
        return \Yii::$app->response;
    }


    /**
     * @param $id
     * @return Certificate
     * @throws NotFoundHttpException
     */
    public function findModel($id)
    {
        $model = Certificate::findOne(['id' => $id]);
        if (!$model) {
            throw new NotFoundHttpException('Шаблон не найден');
        }

        return $model;
    }

}

views/certificate/create.php
<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $template app\models\Template */
/* @var $certificate app\models\Certificate */
/* @var $blocks app\models\Block[] */
/* @var $certValue app\models\CertValue */

$this->title = 'Создание сертификата';
$this->params['breadcrumbs'][] = ['label' => 'Сертификаты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="font-create">

    <h1><?= Html::encode($this->title) ?></h1>


    <div class="font-form">

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($certificate, 'email')->textInput(['maxlength' => true]) ?>
        <?= $form->field($certificate, 'template_id')->label(false)->hiddenInput(['value' => $template->id]) ?>

        <?php foreach ($blocks as $block) : ?>
            <?= $form->field($certValue, '['.$block->id.']value')->label($block->type->title)->textInput(['maxlength' => true]) ?>

        <?php endforeach; ?>
        <div class="form-group">
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>


</div>

views/certificate/index.php
<?php

use app\models\Template;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model Template[] */

$this->title = 'Список сертификатов';
$this->params['breadcrumbs'][] = $this->title;
?>


<table class="table">

    <h4>Список доступных сертификатов</h4>
    <?php foreach ($model as $item) : ?>
        <tr>
            <td><?= $item->title; ?></td>
            <td>
                <a href="<?= Url::to(['/certificate/create', 'id' => $item->id]); ?>" class="btn btn-success">
                    Создать
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

views/certificate/my.php
<?php

use app\models\Certificate;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Мои сертификаты';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="font-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => '{items}',
        'columns' => [
            'id',
            [
                'attribute' => 'title',
                'value' => function (Certificate $model) {
                    return $model->template->title;
                }
            ],
            [
                'header' => '',
                'format' => 'raw',
                'value' => function (Certificate $model) {
                    return Html::a('Просмотреть', ['/certificate/view', 'id' => $model->id], [
                        'class' => 'btn btn-success'
                    ]);
                }
            ],
            [
                'header' => '',
                'format' => 'raw',
                'value' => function (Certificate $model) {
                    return Html::a('Скачать', ['/certificate/download', 'id' => $model->id], [
                        'class' => 'btn btn-primary',
                        'target' => '_blank'
                    ]);
                }
            ]

        ],
    ]); ?>
</div>

views/certificate/view.php
<?php

/* @var $this yii\web\View */

/* @var $model app\models\Certificate*/

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;

$this->title = 'Сертификат №' . $model->id;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="certificate-view">
    <a href="<?=Url::to(['/certificate/download', 'id' => $model->id]);?>" class="btn btn-success" target="_blank">
        Скачать
    </a>
    <hr>
    <img src="<?=Url::to(['/certificate/img', 'id' => $model->id]);?>" alt="">
</div>